server:
  port: 8081

spring:
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
    mcp:
      client:
        name: sgerard-mcp-hands-on
        type: SYNC
        sse:
          connections:
            server1:
              url: http://localhost:8080
        toolcallback:
          enabled: true