spring:
  application:
    name: mcp-hands-on
  main:
    banner-mode: off

  ai:
    mcp:
      server:
        name: sgerard-hands-on-stdio
        version: 1.0.0
        stdio: true

logging:
  pattern:
    console: